# Generated by Django 3.2.7 on 2021-10-05 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='', max_length=10)),
                ('by_in', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('result', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('date', models.DateField()),
                ('rate', models.CharField(default='', max_length=100)),
                ('kind', models.CharField(default='', max_length=100)),
                ('max_players', models.CharField(default='', max_length=10)),
                ('memo', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
