# Generated by Django 3.2.7 on 2022-05-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rate', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
